exports.ActivityAction = Object.freeze({
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    MOVE: 'MOVE',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ASSIGN: 'ASSIGN',

    ADD_MEMBER: 'ADD_MEMBER',
    UPDATE_MEMBER: 'UPDATE_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',

    CREATE_USER: 'CREATE_USER',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    REVOKE_ACCESS: 'REVOKE_ACCESS',

    UPLOAD_ATTACHMENT: 'UPLOAD_ATTACHMENT',
    DELETE_ATTACHMENT: 'DELETE_ATTACHMENT',

    EXTENSION_REQUEST: 'EXTENSION_REQUEST',
    EXTENSION_APPROVE: 'EXTENSION_APPROVE',
    EXTENSION_REJECT: 'EXTENSION_REJECT',
    LATE_COMPLETION: 'LATE_COMPLETION',
});

exports.ActivitySource = Object.freeze({
    SYSTEM: 'SYSTEM',
    SECURITY: 'SECURITY',

    USER: 'USER',
    PROJECT: 'PROJECT',
    BOARD: 'BOARD',
    COLUMN: 'COLUMN',
    TASK: 'TASK',
    COMMENT: 'COMMENT',
    ATTACHMENT: 'ATTACHMENT',

    ORGANIZATION: 'ORGANIZATION',
    DEPARTMENT: 'DEPARTMENT',
    TEAM: 'TEAM',

    AI: 'AI',
});